//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Access_data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_R_INVOICE
    {
        public System.Guid Invoice_ID { get; set; }
        public Nullable<System.Guid> BA_ID { get; set; }
        public string Invoice_No { get; set; }
        public string Cust_Code { get; set; }
        public string Bill_To_Company { get; set; }
        public string Delivery_Address { get; set; }
        public string Delivery_To_Person { get; set; }
        public string Delivery_To_Tel { get; set; }
        public string Report_To_Comany { get; set; }
        public string Reports_To_Address { get; set; }
        public string Reports_To_Tel { get; set; }
        public Nullable<System.DateTime> Invoice_Issue_Date { get; set; }
        public Nullable<System.DateTime> Invoice_Date_Override { get; set; }
        public Nullable<decimal> Total_Invoice_Amount_Inc_Vat { get; set; }
        public string CreditTerm { get; set; }
        public string Status_Code { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
    }
}
